benchmarks:
  - ae
  - dj
  - ghz
  - qft
  - qftentangled
  - qnn
  - qpeexact
  - qpeinexact
  - random
  - realamprandom
  - su2random
  - twolocalrandom
  - wstate
target: equal1
emulate: True
min_qubits: 4
max_qubits: 17